safe: true
baseurl: /unitymappingfactory
lsi: false

pygments: true
markdown: redcarpet
redcarpet:
  extensions: [:fenced_code_blocks]

exclude: [.gitignore]
  
navigation:
- text: Home
  title: Home  
  fullurl: /index.html
  url: /
- text: Design
  title: Design Considerations
  fullurl: /design.html
  url: /design.html